apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8tz.serviceName" . }}
  namespace: {{ include "k8tz.namespace" . }}
  labels:
    {{- include "k8tz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "k8tz.selectorLabels" . | nindent 4 }}
