{{- if .Values.vmagent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: etcd-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  healthcheck-client.crt: {{ .Files.Get "files/certs/etcd/healthcheck-client.crt" | b64enc | quote }}
  healthcheck-client.key: {{ .Files.Get "files/certs/etcd/healthcheck-client.key" | b64enc | quote }}
  ca.crt: {{ .Files.Get "files/certs/etcd/ca.crt" | b64enc | quote }}
{{- end }}
