---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: kubernetes-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-grafana.labels" . | nindent 4}}
spec:
  configMapRef:
    key: dashboard
    name: kubernetes-grafana
  contentCacheDuration: 0s
  folder: kube
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 876000h
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-grafana
  labels:
    {{- include "prometheus-grafana.labels" . | nindent 4}}
data:
{{- range $path, $bytes := .Files.Glob "dashboards/kubernetes.json" }}
  dashboard: |
{{ printf "%s" $bytes | indent 4 }}
{{- end }}
---