apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-internet
  namespace: {{.Release.Namespace}}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: kubeblocks
    apps.kubeblocks.io/component-name: mongodb
    kubeblocks.io/role: primary
  sessionAffinity: None
  type: LoadBalancer