# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeSelector: {}

monitor: true

cluster:
  replicas: 3
  storage: 20Gi
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 200m
      memory: 200Mi

backup:
  # 开启自动备份
  enabled: true
  # UTC 时区
  cronExpression: 10 00 * * *
  # 使用 datafile 进行备份，如果存储支持快照，可以指定为 volume-snapshot
  method: datafile
  # 是否开启 PITR
  pitrEnabled: false
  # 备份集保留时长
  retentionPeriod: 7d
  # BackupRepo
  repoName: backuprepo-default