name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build apps image
    if: startswith(github.event.comment.body, '/imagebuild_apps')
    runs-on: ubuntu-18.04
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Auto build image
        id: autobuild
        env:
          domain: default
          repo: default
          prefix: default
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          sealos: 4.0.0-alpha.11
        run: |
          app=`echo "$commentbody"| awk '{print $2}'`
          version=`echo "$commentbody"| awk '{print $3}'`
          branch=`echo "$commentbody"| awk '{print $4}'`
          echo "deb [trusted=yes] https://apt.fury.io/labring/ /" | sudo tee /etc/apt/sources.list.d/labring.list
          sudo apt update
          sudo apt install sealos
          echo "app: $app"
          echo "version: $version"
          echo "branch: $branch"
          git checkout $branch
          echo "start to build $app:$version"
          export PATH=${PATH}:$(pwd)
          #wget https://github.com/labring/sealos/releases/download/v$sealos/sealos_${sealos}_linux_amd64.tar.gz
          #tar -zxvf sealos_${sealos}_linux_amd64.tar.gz
          #chmod a+x sealos
          #sudo mv sealos /usr/bin/
          #wget https://sealyun-home.oss-accelerate.aliyuncs.com/images/buildah.linux.amd64 --no-check-certificate -O buildah && chmod a+x buildah
          #sudo mv buildah /usr/bin/
          cd $app
          filename=Kubefile
          if  [ -f Dockerfile ]; then
            filename=Dockerfile
          fi
          sudo sealos login $domain -u $username -p $password
          sudo sealos build -t $domain/$repo/$prefix-$app:$version -f $filename .  > output.log
          sudo sealos push $domain/$repo/$prefix-$app:$version >> output.log
          echo "sealos push $domain/$repo/$prefix-$app:$version success"
          body="$(cat output.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            ${{ steps.autobuild.outputs.body }}
            ```
            detail log please view [autobuild](https://github.com/${{ github.repository_owner }}/bitring-template-project/actions/workflows/autobuild.yml)
